name: Build and deploy site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Detect site source
        id: detect
        run: |
          build=false
          publish_dir=""

          if [ -d "docs" ]; then
            publish_dir="docs"
          fi

          if [ -d "_site" ]; then
            publish_dir="_site"
          fi

          if [ -f "Gemfile" ] || [ -f "_config.yml" ]; then
            name: Build and deploy site to GitHub Pages

            on:
              push:
                branches: [main]
              workflow_dispatch:

            jobs:
              build-deploy:
                runs-on: ubuntu-latest
                steps:
                  - name: Checkout repository
                    uses: actions/checkout@v4
                    with:
                      submodules: true
                      fetch-depth: 0

                  - name: Detect site source
                    id: detect
                    run: |
                      build=false
                      publish_dir=""

                      if [ -d "docs" ]; then
                        publish_dir="docs"
                      fi

                      if [ -d "_site" ]; then
                        publish_dir="_site"
                      fi

                      if [ -f "Gemfile" ] || [ -f "_config.yml" ]; then
                        build=true
                        publish_dir="_site"
                      fi

                      echo "build=${build}" >> $GITHUB_OUTPUT
                      echo "publish_dir=${publish_dir}" >> $GITHUB_OUTPUT

                  - name: Show detection results
                    run: |
                      echo "build=${{ steps.detect.outputs.build }}"
                      echo "publish_dir='${{ steps.detect.outputs.publish_dir }}'"

                  - name: Setup Ruby and Bundler (for Jekyll build)
                    if: steps.detect.outputs.build == 'true'
                    uses: ruby/setup-ruby@v1
                    with:
                      ruby-version: '3.1'
                      bundler-cache: true

                  - name: Install dependencies (for Jekyll build)
                    if: steps.detect.outputs.build == 'true'
                    run: |
                      gem install bundler
                      bundle config set --local path vendor/bundle
                      bundle install --jobs 4 --retry 3

                  - name: Build site with Jekyll
                    if: steps.detect.outputs.build == 'true'
                    run: |
                      bundle exec jekyll build --verbose --trace

                  - name: Skip deploy when no site found
                    if: steps.detect.outputs.publish_dir == ''
                    run: |
                      echo "No site found to publish (no docs/ or _site/ and no Jekyll sources). Skipping deploy."

                  - name: Deploy to GitHub Pages
                    if: steps.detect.outputs.publish_dir != ''
                    uses: peaceiris/actions-gh-pages@v3
                    with:
                      github_token: ${{ secrets.GITHUB_TOKEN }}
                      publish_dir: ${{ steps.detect.outputs.publish_dir }}
                      commit_message: "Deploy site: ${{ github.sha }}"

            # Notes:
            # - This workflow will deploy from `docs/` or `_site/` if present, or build a Jekyll site when a `Gemfile` or `_config.yml` is detected.
            # - If your site lives in another folder, update the detection or set `publish_dir` explicitly.
            # - Make sure GitHub Pages is configured to serve from the `gh-pages` branch (or check Pages settings if you use a different branch).
        if: steps.check.outputs.build == 'true'
